<blockquote>
	<p>To educate people against BrainWallet type passphrase algorithm's for sensitive information.   Let this be a standing database of all compromised BitCoin wallet's generated by such methods.</p>
	<p>Source will be available for people to host and run against dictionary type attacks locally. The source has the option built in and enabled to upload results to our global database available openly and publicly on this site.</p>
</blockquote>
<blockquote>
	<p><a  href="https://github.com/walletbrute/WalletBrute"><img src="<?php echo APP_IMAGES; ?>/github.png" style="float:left;margin-right:10px;height:40px;"><img src="<?php echo APP_IMAGES; ?>/down.png" style="float:left;margin-top:-2px;margin-right:10px;height:42px;"><span style="font-size:1.5em;">Checkout or Download the Latest Source from GitHub</span></a></p>
<p><i><a href="LICENSE">GNU General Public License</a></i></p>
</blockquote>