<blockquote>
	<p>To educate people against BrainWallet type passphrase algorithm's for sensitive information.   Let this be a standing database of all compromised BitCoin wallet's generated by such methods.</p>
	<p>Source will be available for people to host and run against dictionary type attacks locally. The source has the option built in and enabled to upload results to our global database available openly and publicly on this site.</p>
</blockquote>
