<div class="alert alert-danger alert-dismissible" role="alert">
  <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
  <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
  <strong>WARNING!</strong><br />Any wallet found in this database or generated by this application is <strong>NOT SECURE</strong>!<br />You will lose any actual currency associated with the address more than likely.
</div>
<blockquote>
	<p>List of known brainwallets and their associated details. Wallets are stored indefinitely, and updated in batches as frequently as possible with current balance and transaction details. Most recent information on specific wallets can be updated manually by re-entering the passphrase. This will bump it to the beginning of the queue depending on your user session.</p>
</blockquote>
<table id="wallets_found" class="display" cellspacing="0" width="100%">
    <thead>
        <tr>
            <th><!--<span class="glyphicon glyphicon-warning-sign" aria-hidden="true"></span>--> Pasphrase</th>
            <th><!--<span class="glyphicon glyphicon-warning-sign" aria-hidden="true"></span>--> Private Key</th>
            <th><!--<span class="glyphicon glyphicon-eye-open" aria-hidden="true"></span>--> Public Address</th>
            <th><!--<span class="glyphicon glyphicon-piggy-bank" aria-hidden="true"></span>--> Balance</th>
            <th><!--<span class="glyphicon glyphicon-transfer" aria-hidden="true"></span>--> Received</th>
            <th><!--<span class="glyphicon glyphicon-calendar" aria-hidden="true"></span>--> Last Updated</th>
            <th><!--<span class="glyphicon glyphicon-calendar" aria-hidden="true"></span>--> Exists</th>
        </tr>
    </thead>

    <tfoot>
        <tr>
            <th><!--<span class="glyphicon glyphicon-warning-sign" aria-hidden="true"></span>--> Pasphrase</th>
            <th><!--<span class="glyphicon glyphicon-warning-sign" aria-hidden="true"></span>--> Private Key</th>
            <th><!--<span class="glyphicon glyphicon-eye-open" aria-hidden="true"></span>--> Public Address</th>
            <th><!--<span class="glyphicon glyphicon-piggy-bank" aria-hidden="true"></span>--> Balance</th>
            <th><!--<span class="glyphicon glyphicon-transfer" aria-hidden="true"></span>--> Received</th>
            <th><!--<span class="glyphicon glyphicon-calendar" aria-hidden="true"></span>--> Last Updated</th>
            <th><!--<span class="glyphicon glyphicon-calendar" aria-hidden="true"></span>--> Exists</th>
        </tr>
    </tfoot>
</table>
